### ISSUE TITLE
Missing functionalities

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#10]
`Explorer.transition-stace space.Clear plot `
	Missing functionality

`Explorer.activate/!.click`
	Missing functionality

`Result.activate/!.click`
	Missing functionality

`Explorer.vector field.Unzoom.click`
	Missing functionality (or runs long without shading plot)
	! Explorer.vector field.Unzoom.doubleclick 	works

======================================================
LEGEND:
ModulesDict:= {Model editor:Editor,Model explorer:Explorer,Result explorer:Result}

**Comment by martindemko** [comment]
'activate!' buttons will be replaced by 'next' and 'prev' buttons for switching between experiments

'Clear plot' buttons may be subject to delay which cannot be predicted or managed
