### ISSUE TITLE
Editor, run parameter synthesis

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#16]
On offline version:

Generate approximation -> Run parameter synthesis

results in error:
Warning: running command '"..//biodivine-ctl//bin//ode_model" ..//Temp//config.689626.json > ..//Temp//result.689626.json 2> ..//Temp//progress.689626.txt' had status 127

**Comment by martindemko** [comment]
this probably happened because of change in the name of model-checker bin. It should be fixed

**Comment by xhajnal** [comment]
Solved with new commit,
ack
