### ISSUE TITLE
Explorer, Selecting same parameter for axes

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#20]
`Explorer.plot(1).setHorizontal(y) ->Explorer.plot(1).setVertical(y) `
results in:
Error:non-numeric argument to mathematical function

![image](https://cloud.githubusercontent.com/assets/23458520/21010353/ea5f150a-bd4b-11e6-9412-b3f7070b7387.png)
**Solve:**
- Please write explicitly to choose different parameters in the Error
 or
- Do not draw such plot at all

**Comment by martindemko** [comment]
those are not parameters but variables and such kind of plot (1-dimensional) is not implemented yet, but it will be

**Comment by martindemko** [comment]
should be OK
