### ISSUE TITLE
Results, Selecting same parameter for axes y,y

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#21]
`Results.plot(1).setHorizontal(y) ->Results.plot(1).setVertical(y) `
results in 
Error: Some duplicate ....
and then both plots (PD and SS) disappear (Fig. 1)

![image](https://cloud.githubusercontent.com/assets/23458520/21010845/9291e8fe-bd4e-11e6-97ea-42228a20e5f4.png)

Then Flow:
`-> Results.addplot() -> Results.plot(1).setHorizontal(x)`

**Problem 2:**
the plot 1 doesn't set horizontal to x and stay hidden (Fig. 2)

![image](https://cloud.githubusercontent.com/assets/23458520/21010603/485e717c-bd4d-11e6-99d8-7e25362a1b91.png)

As you can see in the image, I have selected 3 plots but only 1 is visualised

**Comment:**
without adding second plot, the feature seems working

**Comment by martindemko** [comment]
As I told before, it is forbidden to use just variables for showing in result plots. It will be handled later, for now use just parameters or combination of parameter and variable

**Comment by martindemko** [comment]
fixed in last commit

**Comment by xhajnal** [comment]
- This feature is designed for exploring of paramaters so, please, choose at least one of them
+ Please select at least one parameter.
