### ISSUE TITLE
Dependent parameters

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#23]
**<MODEL:>**
```

VARS: x,y
CONSTS: k1,1; k2,1
PARAMS: deg_x,0,1; deg_y,0,1

EQ: x = k1*hillm(y,5,5,1,0) - deg_x*x - deg_y*y
EQ: y = k2*hillm(x,5,5,1,0) 

VAR_POINTS: x: 2500, 10; y: 2500, 10

THRES: x: 0, 15
THRES: y: 0,4,8, 15
```

`Editor.generateApproximation -> Editor.runParameterSynthesis `
results in Crash:

Warning in as.data.table.list(x) :
  Item 2 is of size 0 but maximum size is 1, therefore recycled with 'NA'
Warning in as.data.table.list(x) :
  Item 2 is of size 0 but maximum size is 1, therefore recycled with 'NA'
Warning in as.data.table.list(x) :
  Item 2 is of size 0 but maximum size is 1, therefore recycled with 'NA'
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    43: rbindlist
    42: <reactive:loading_ps_file> [E:\BioDivine\biodivineGUI/server.R#1870]
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3317]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3334]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3348]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3381]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3399]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3500]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#1996]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3517]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3531]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3568]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#3580]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#2010]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: loading_ps_file
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#2021]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    45: <Anonymous>
    44: stop
    43: loading_ps_file
    42: <reactive:visible_ps_plots> [E:\BioDivine\biodivineGUI/server.R#2081]
    31: visible_ps_plots
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#2302]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: visible_ps_plots
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#2324]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: visible_ps_plots
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#2347]
     1: runApp
Warning: Error in rbindlist: Item 3 has 1 columns, inconsistent with item 1 which has 2 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Stack trace (innermost first):
    33: <Anonymous>
    32: stop
    31: visible_ps_plots
    30: observerFunc [E:\BioDivine\biodivineGUI/server.R#2359]
     1: runApp
ERROR: [on_request_read] connection reset by peer

**Comment by xhajnal** [comment]
ack

**Comment by xhajnal** [comment]
reopened because of results with empty list solving

**Comment by martindemko** [comment]
should be solved in last commit in branch switch_between_experiments
