### ISSUE TITLE
Editor, no. of threads

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#3]
Editor.no/. of threads.changelocation(advanced settings) 
(move <no/. of threads> to advanced settings )
OR
(remove this function and set maxi no. of threads)

======================================================
LEGEND:
ModulesDict:= {Model editor:Editor,Model explorer:Explorer,Result explorer:Result}

**Comment by martindemko** [comment]
implicitly it is now set up to max no. of threads but it will be in advanced settings

**Comment by xhajnal** [comment]
ack
