### ISSUE TITLE
Explorer, trajectory on zoomed plot

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#31]
`Explorer.SS.plot(1).zoom -> Explorer.VF.plot(1).doubleclick (to view trajectory) `

Problem:
Trajectory is not drawn in SS plot

Problem 2:
Not shown even after unzooming the SS plot.

![image](https://cloud.githubusercontent.com/assets/23458520/21297818/25f5203a-c587-11e6-846a-2e3572788051.png)

**Comment by martindemko** [comment]
I don't get it, please, explain yourself more or send me an email

**Comment by martindemko** [comment]
missundestanding
