### ISSUE TITLE
Explorer, parameter value

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#39]
Explorer.parameter(deg_x).up | Explorer.parameter(deg_x).up

When increasing value of parameter rapidly, gui results in cycle of changes

**Comment by xhajnal** [comment]
Same for Explorer.parameter().setValue

**Comment by xhajnal** [comment]
resolved by commit stable_parameters in branch just_one_experiment

**Comment by daemontus** [comment]
Fixed in clean-up (debounce)
