### ISSUE TITLE
changes of model, parameter synthesis

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#43]
`Editor.generateApproximation().click -> Editor.runParameterSynthesis().click -> Editor.changeModel() -> Editor.generateApproximation().click `

What should tab Results show in this moment?
- old result
- blank
- other

**Comment by martindemko** [comment]
It is and it should be blank so the user won't be confused by different models used for result expl. and model expl. tabs.

**Comment by xhajnal** [comment]
Well, it isn't blank. (will be solved tomorrow, ok?)
