### ISSUE TITLE
Explorer, drawing no plot

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#6]
`Flow: Explorer.addPlot(x,y) -> Explorer.deletePlot((x,y))`
result: "transition-state space is drown" 
drawing progress on deleting last plot

======================================================
LEGEND:
ModulesDict:= {Model editor:Editor,Model explorer:Explorer,Result explorer:Result}
"Flow"	Serie of action in GUI (symbol "->" means using with sufficient delay and symbol "|" means without delay(for example doubleclick))

**Comment by martindemko** [comment]
It's caused because of reactivity inside R Shiny and can be fixed only by removing of this progress bar or by changing of text inside progress bar to smth neutral like "waiting for transition-state space"

**Comment by martindemko** [comment]
rewritten

**Comment by xhajnal** [comment]
ack
