### ISSUE TITLE
please more highlight for "Out of sync" warning (UX)

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#63]
I have merely spotted this warning - Warning: This model is out of sync with current contents of the model editor.

please do some highlight. Thanks.

**Comment by martindemko** [comment]
It's exactly the same as it was in the previous version and nobody complained about it but I'm opened to suggestions. It's HTML so it's easy to change.

**Comment by martindemko** [comment]
It's big and red now.
