### ISSUE TITLE
Missing green highlight on TCA results 

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#64]
After a TCA is complete for the first time, the 'TCA Result' button should be green.

**Comment by martindemko** [comment]
If no previous data were loaded so any new result source is directly loaded (meaning you can already Add plot) and therefore it's no meaning for having a green button. Green colour means that new data were produced, different from loaded ones. I think it's more pleasant than to let user first click on one button to actually load data and than to another button to add a plot.

**Comment by martindemko** [comment]
Now you don't even need to press the Add plot button. The very first results are loaded and displayed automatically.
