### ISSUE TITLE
Specify which results I have downloaded (UX)

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#65]
maybe like this:
PS_results / TCA_results / Imported_results

**Comment by martindemko** [comment]
If you look at tooltip it will tell you that you are downloading current loaded results. Maybe some other name would be better.

**Comment by xhajnal** [comment]
I mean the file.

**Comment by martindemko** [comment]
It's not very meaningful because every browser handles this name by its own. Some don't use it at all.

**Comment by martindemko** [comment]
Ok, it's done, maybe somebody will appreciate it
