### ISSUE TITLE
Explorer, set axes

### ISSUE THREAD

**Issue by xhajnal** [sybila/biodivineGUI#7]
Flow: Explorer.plot(1).setHorizontal(#) | Explorer.plot(1).setVertical(#)
result: vertical axis not set
add GUI delay on setting plot axis value

======================================================
LEGEND:
ModulesDict:= {Model editor:Editor,Model explorer:Explorer,Result explorer:Result}
"Flow"	Serie of action in GUI (symbol "->" means using with sufficient delay and symbol "|" means without delay(for example doubleclick))

**Comment by martindemko** [comment]
I hope this is reduced due to the default values in every new added plot

**Comment by xhajnal** [comment]
Well, yes it is reduced, but not solved.
